# Generated by Django 4.2.5 on 2026-04-20 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(db_index=True, max_length=2000)),
                ("rules", models.JSONField(default=dict)),
                (
                    "extraction_type",
                    models.CharField(
                        choices=[("html", "HTML"), ("json", "JSON")],
                        default="html",
                        max_length=20,
                    ),
                ),
                (
                    "frequency_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="How often (in minutes) this source should be scraped.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapedResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "has_changed",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        help_text="True if scraped data differs from the previous result for this source.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="scraper.scrapingsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
